### ISSUE TITLE
Provide support for iOS 9 users

### ISSUE THREAD

**Issue by Matchstic** [Matchstic/Extender-Installer#13]
Users of iOS 9 also have an app-based jailbreak from PanGu. Supporting these people shouldn't be too hard, with maybe a need to revise the notification banners API utilised.

**Comment by inoicouldalwaysturn2u** [comment]
Any updates on this? It would be amazing to get this for iOS 9. I saw a number of people asking on Reddit too.

I wish I could help coding wise. But instead I could help donate if that's a thing for you.

**Comment by urherenow** [comment]
I've read that people with actual developer accounts have it installed with impactor. So why block IOS 9 users from installing via cydia?

**Comment by technodrome** [comment]
Is there any update on this or did this problem go into dead beetle mode?

**Comment by Matchstic** [comment]
iOS 9 support as available on the new-backend fork
