### ISSUE TITLE
Provide option to disable notifications

### ISSUE THREAD

**Issue by ryanmunk** [Matchstic/Extender-Installer#14]
A simple option to disable notifications.

**Comment by cyanisaac** [comment]
I'm happy to have signing notifications, but an option to disable the "No applications need resigning at this time" notifications would be nice. Perhaps an option for what to allow / not allow would be good.

![excessive notifications](http://i.imgur.com/8ql3H3f.png)

**Comment by Matchstic** [comment]
Option has now been added for v0.3.2, and disables these notifications by default.
