### ISSUE TITLE
Notification after respring 

### ISSUE THREAD

**Issue by A1p1n3** [Matchstic/Extender-Installer#15]
Often times I get the "no application needs resigning at this time" notification if my device is left on standby for too long, as well as when my device resprings. I believe this is a feature but this implementation turns annoying while looking through NC or lockscreen notifications.

**Comment by Matchstic** [comment]
Issue has been fixed with commit https://github.com/Matchstic/Extender-Installer/commit/5fa33f3c199477dafb73e7da4fc939fea4128116 - an option is available to toggle these notifications, and has them disabled by default.
