### ISSUE TITLE
rebooting after v 0.3

### ISSUE THREAD

**Issue by schults** [Matchstic/Extender-Installer#19]
Today´s after your latest release of extender installer my mach portal it´s not working properly, I mean, before the release I had no problem using it but after the release my iPhone reboot twice. I don´t know what happened but I think might have something to do with this latest update. Can you please check it for us? Thank you for your work.

**Comment by Matchstic** [comment]
Can you provide some more information please?

Such as:
- Were you jailbroken when the reboots occurred?
- When was the last time mach_portal got re-signed?
- Has this issue re-occurred again?

Since there's a multitude of reasons your phone may reboot randomly, especially using mach_portal as your jailbreak, this will be extremely difficult to pin down if it is my fault.

**Comment by schults** [comment]
I'm using iPhone 7+ Plus with iOS 10.1.1 b3 mach_portal. Well, last re-sign was 4 days and 5
hours ago. About he supposed error, it occurred after the latest update I think, and I did note that occurred twice. I realized that I was without the jailbreak when I tried to use one of my tweaks ( I have only 7 installed). I'll keep looking it and with happened again I'll send you email. Thank you again for your work

**Comment by schults** [comment]
Look what's happening: I pressed the re-sign button, the app do what it needs to do, and it closes automatically after. When I try to open the app again, one window pop-up with the Apple ID and password open again(it looks like it's trying to do the process again) and than it closes again. It's doing that all the time now. Sometimes appears one faster error that I only could read as : buffer error cpp 285 cannot...It's not re-signing the mach_portal. Please help me. What can I do to fix this ?

PS: it's not appearing none notifications on my notifications screen. Is it right or should it appear?

**Comment by schults** [comment]
This is the faster error that appears. I just got to take the picture because I recorded the screen and paused when the error appeared. It's no re-signing the mach_portal and it's kinda entering in some kind of loop when I open the app again after I pressed this button.

**Comment by Matchstic** [comment]
Checking to see if these issues are now resolved?

**Comment by schults** [comment]
Yes it's resolved. I didn't get any error of his anymore. By the way, in the extender I resigned but the time there didn't "erase" and don't restart from 0 day. For example my mach_portal it's with more than 7 days and 10 hours now. And my tweaks are working. Is it mean that the re-sign button worked?thanks for your work.

**Comment by Matchstic** [comment]
Try tapping the Re-sign button in the Installed tab, that will manually start a re-sign for mach_portal.
