### ISSUE TITLE
0.3.2 displays with iPhone 4/s layout on iPhone 5s

### ISSUE THREAD

**Issue by joemerlino** [Matchstic/Extender-Installer#22]
Title says it all, after the new update the app shows black lines at the top and bottom of the display.

**Comment by Matchstic** [comment]
I'm not sure why this would occur in all honesty. Searching up on this issue shows me that it can happen when Auto-Layout believes the app was not updated for iPhone 5 onwards support, which is not the case here.

**Comment by A1p1n3** [comment]
Im curious to see wether this is just iOS 10 or not because this did not happen on a test device of mine running on iOS 9/10

**Comment by A1p1n3** [comment]
Auto-Layout should not be the cause of this because if it was it would happen on every 4in screened device

**Comment by Matchstic** [comment]
No longer need Extender as a base in the new-backend fork
