### ISSUE TITLE
Unable to sign in with 0.3.2

### ISSUE THREAD

**Issue by iPhoneAddict** [Matchstic/Extender-Installer#23]
I am unable to sign in with the latest release 0.3.2 whereas it is working correctly with 0.3.1
My password is using a special character

**Comment by Matchstic** [comment]
Which special character is it? I'll create an Apple ID this end that uses it in the password to test.

**Comment by iPhoneAddict** [comment]
it’s « & »

Thank you.

**Comment by Matchstic** [comment]
This bug has been resolved with commit https://github.com/Matchstic/Extender-Installer/commit/b941e30d4bffc961ade4d2874db2fb64cb711492
