### ISSUE TITLE
Impossible to use in parallel 2 jailbroken devices iPhone + iPad

### ISSUE THREAD

**Issue by iPhoneAddict** [Matchstic/Extender-Installer#24]
I get the error provision.cpp for pending certificate when trying to resign yalu with Extender on a second device (v0.3.1 as new v0.3.2 does not allow me to sign-in probably due to special characters regression).

First, I used extender on my iPad Pro and it is working.
Then I was getting the error on my iPhone when trying to resign Yalu.  
I did the revoke certificate action with impactor on my Mac (2 certificates said to be revoked)
then signed in and resigned yalu on my iPhone first. It worked.
Now i get the error when trying to resign Yalu on my iPad.
Seems like only one device can use extender.

**Comment by Matchstic** [comment]
This is a known issue, and seems to be an accidental limitation in saurik's code; my guess using Impactor on multiple computers will give the same issue.

I am looking into the exact root cause, though I'm  not overly sure I will be able to fix this. Please see issue #4 for progress updates.

**Comment by iPhoneAddict** [comment]
Not sure to catch you.

For sure, using impactor on my iPad and my iPhone separately on the same iMac does not generate any error.
They are both jailbroken with impactor/Yalu with error message and working.

Only using Extender to resign generate this message on the second device in order of launching Extender.
Reseting through impactor trick is freeing the process (tested once with success, reversed the allowed device from iPad to iPhone).

**Comment by iPhoneAddict** [comment]
With no error message.

Sorry.
