### ISSUE TITLE
[Request] Ability to drag and drop IPA 

### ISSUE THREAD

**Issue by AppleTechy** [Matchstic/Extender-Installer#25]
Would be awesome if you modified the app to allow you to either search the downloads folder to click and add an ipa file to be signed. Or after downloading IPA when clicked on in Filza and "shared" that Extender would be able to see the IPA and have the ability to sign it for you. This would allow you to easily sign apps without having to manually connect into your computer the first time to try and install.

**Comment by Matchstic** [comment]
This feature is already available? It is possible to open an IPA from Safari directly into Extender, by the "Open in..." dialog.
