### ISSUE TITLE
Yalu not showing on installed list

### ISSUE THREAD

**Issue by slimschutte** [Matchstic/Extender-Installer#28]
When clicking on "installed " no apps showing up at all

**Comment by Matchstic** [comment]
You need to sign in to Extender with the same Apple ID used to sign Yalu with via Impactor. Otherwise, my code cannot find it.

**Comment by slimschutte** [comment]
Certificate has ran out now and I can't remember what Apple ID I used anyway I can find out without re-jail breaking ?

**Comment by Matchstic** [comment]
Yep; check in Settings > General > Device Management. The Apple ID used will be the one there that has Yalu listed under it.

Matt

**Comment by slimschutte** [comment]
Yalu has disappeared from there
