### ISSUE TITLE
"Your Apple ID or password is incorrect" notification

### ISSUE THREAD

**Issue by Matchstic** [Matchstic/Extender-Installer#29]
This issue is caused by the user's password being inaccessible whilst the device is locked. A change to the code storing data into the Keychain should resolve this, along with a function in extrainst_ to port existing Keychain data to being accessible when locked.

**Comment by darek80** [comment]
Hello... extender it not let me access with my id from Apple, I've read your explanation but not understood well what you need to do, clear the key and unlock code but does not work please could you help me

**Comment by Matchstic** [comment]
You'll need to wait until I finish the fix for this issue; there's nothing at the moment you can do on your end I'm afraid.

**Comment by darek80** [comment]
Ok thank you

**Comment by Matchstic** [comment]
This issue is now resolved by commit https://github.com/Matchstic/Extender-Installer/commit/f2861b287032be70d747b1a0945333f83556844f, which effectively sidesteps this and any other potential Keychain issues by queuing re-signs when the device is locked to be undertaken when the device is next unlocked.
