### ISSUE TITLE
Even after a re-sign, apps may not remain signed after a reboot

### ISSUE THREAD

**Issue by Matchstic** [Matchstic/Extender-Installer#30]
As per the title; apps may crash as if they are not signed after a reboot, even if they have been inside the 7 day window, and launch when jailbroken.

**Comment by Matchstic** [comment]
Revoking certificates before re-signing seems to prevent this issue.

Therefore, my current working theory is that Extender and Impactor both work as expected OUTSIDE the 7 day window, i.e. an application has "expired". This would indicate that something _odd_ is happening Apple's end, when checking the validity of a certificate after a reboot. Perhaps a re-sign occurring within the 7 day window does not update on Apple's end, or something? Revoking certificates and then re-signing I assume sidesteps this by invalidated anything and going from a clean slate every time.

To resolve this, either I'll have to force auto-revoking every re-sign (very much not ideal), or work out what is going on Apple's end when checking certificate validity on a reboot.

**Comment by Matchstic** [comment]
This is also the same bug where a re-sign will repeat for a few days.

From looking into this, I have found that the ExpirationDate of the embedded.mobileprovision file does NOT change until after a re-sign occurs past then. Therefore, either Apple's server caches and re-vends the same certificate until it expires, or the iOS device caches it in a similar manner when installing an application. My money is on the former; will need to see how to remove a certificate for a single application.

**Comment by gerbil-snot** [comment]
Having this problem unfortunately, same problem with the alternative "Ext3nder". I can't use either to resign Yalu102; however, they did work for the first month after downloading them. Hope this bug gets fixed soon, a very useful tool!

**Comment by gerbil-snot** [comment]
It seems that it works after a manual reboot, but crashes after one of the random reboot-crashes due to the jailbreak still being buggy.

**Comment by Matchstic** [comment]
Issue has been resolved. Huzzah.
