### ISSUE TITLE
I don't even know what to call this bug

### ISSUE THREAD

**Issue by gerbil-snot** [Matchstic/Extender-Installer#32]
Strange bug that causes the app to constantly rebuild the database, check for apps that need signing, and then saying there are no applications needing signing. I got about 80 notifications within the span of 5 minutes. Trying to open the app only causes it to crash, and reinstalling had no solution. I was able to fix this by very quickly open the app, going to the More tab, and signing out. The bug didn't stop there though. After trying to sign back in, it would rebuild the database with 0 entries. I fixed this by signing out and using a new app-specific password. Not entirely sure what caused this, it began happening after updating some apps in Cydia and respringing.

**Comment by A1p1n3** [comment]
Are you able to produce a crash log ? if so can you link it ?

**Comment by gerbil-snot** [comment]
What would be the best way of finding the crash reports? I didn't have CrashReporter downloaded at the time. I can do it through iTunes right? What would I be looking for exactly?

**Comment by timonline** [comment]
I believe I am facing the same issue, app keeps throwing out notifications and it can't be launched because it crashes.

I couldn't even follow @gerbil-snot's advise because it crashes too quickly for me to sign out.

Here is the the crash log:

[Extender Crashlog.txt](https://github.com/Matchstic/Extender-Installer/files/1389659/Extender.Crashlog.txt)

**Comment by Matchstic** [comment]
@gerbil-snot  @timonline This crashing issue is one I'm working on, albeit very slowly. I'm going to set aside some time this coming week to get it done.

**Comment by gerbil-snot** [comment]
Thank you for taking the time to look into these issues. This app is working very well and I would hate to have to try an alternative like the glitchy Ext3nder, very much appreciated. I would like to also know what  caused it, as it only happened the one time and I haven't been able to duplicate my actions to cause this issue again.

**Comment by Matchstic** [comment]
@gerbil-snot @timonline I've made a couple of changes seeing as I had some free time; does this build work? Install via iFile or Filza and then respring. 

Link: https://www.dropbox.com/s/7f4yzaaztrn2qwd/com.matchstic.Extender-Installer_0.3.4-2_iphoneos-arm.deb?dl=0

**Comment by gerbil-snot** [comment]
I'll install and let you know if it does happen again, but it hasn't happened again since that first time not sure how long it could be for it to happen again (if it does happen again). It'd be nice to know what caused the problem so I could duplicate my actions to really see if the problem still exists. I'll keep you posted.

**Comment by gerbil-snot** [comment]
It seems the issue is still persisting even after using the new build you provided. I was able to stop it again with the same method as before luckily. Both Extender and CrashReporter were going bezerk. This was caused after installing BigShotJb from Cydia, rebooting, and then re-entering a jailbroken state. I was getting a bit worried after letting it go bezerk for about 5 minutes because of the intense heat my phone was putting off. 

Here's the CrashReport:
https://www.dropbox.com/s/fhxh1b9nqiuvl5y/ExtenderCrashLog.txt?dl=0

**Comment by Matchstic** [comment]
Notes for myself:

- Downgrading to 0.3.3, signing in, then upgrading to 0.3.4 works fine
- If no matching applications to the currently signed-in account's Team ID are present, crash occurs

**Comment by Matchstic** [comment]
This is no longer an issue in the newly rewritten application, ReProvision. It should be released soon!
