### ISSUE TITLE
Crashes on start for iPhone 5 10.3.3

### ISSUE THREAD

**Issue by ColdHeat** [Matchstic/Extender-Installer#34]
With the release of h3lix I can finally jailbreak an old iPhone 5 I have. However, Extender: Reloaded seems to crash on start so I can't get it to auto sign the h3lix app for me. 

From what I can tell looking at julioverne's extender, could this be due to the 32 bit architecture? 

I haven't used a jailbroken phone in awhile but happy to help get crash logs with some guidance.

**Comment by Matchstic** [comment]
Correct, 32-bit is not supported by Extender due to saurik only compiling it for 64-bit.
