### ISSUE TITLE
Crashing on iOS 10.0.2 on 5C

### ISSUE THREAD

**Issue by jhiean** [Matchstic/Extender-Installer#35]
Everytime i've open extender reloaded, it always crashes.. please fix thanks

**Comment by xMarkSt** [comment]
Same problem on iOS 10.3.3 iPad 4. Even after 0.3.4-2 update.

**Comment by Matchstic** [comment]
Both the iPhone 5C and iPad 4 are not 64-bit, which the original Extender requires, hence the crash. I’m working every now and again on an alternative backend that will solve this.
