### ISSUE TITLE
[Error] maxQuantity

### ISSUE THREAD

**Issue by gerbil-snot** [Matchstic/Extender-Installer#37]
What is this? How can I fix it?

**Comment by georgesmhanna** [comment]
I guess it's related to the error we got on Impactor lately. Extender should be updated to the latest version!

**Comment by seevik2580** [comment]
downgrade from 0.3.4-2 to 0.3.4 ... this helps me, and extender works again for me with no errors :)

**Comment by gerbil-snot** [comment]
This worked, thank you.
