### ISSUE TITLE
postrm: Bad CPU type in executable

### ISSUE THREAD

**Issue by Canorus** [Matchstic/Extender-Installer#38]
I don't know what is causing this but I failed to install this extension: error message says Bad CPU type in executable. Capture image attached.

iphone10,6 11.1.2
![exntenderreloaded](https://user-images.githubusercontent.com/7209435/39196444-1838ef20-481d-11e8-9a10-afd8a71ac9e7.png)

**Comment by Matchstic** [comment]
I have the same issue. It seems that when dpkg forks to run the postrm script, it is killed by the kernel due to only launchd only being able to do such forking. It's an issue with Electra IMO, and have reported it in the past.

**Comment by Canorus** [comment]
I see… so I might have to look forward to the Electra update. Thank you for the reply :)

**Comment by Matchstic** [comment]
This is no longer an issue in the newly rewritten application, ReProvision. It no longer needs any scripts like postrm to be run, and should be released soon!
