### ISSUE TITLE
[Error] ios/submitDevelopmentCSR =7460

### ISSUE THREAD

**Issue by Matchstic** [Matchstic/Extender-Installer#4]
This error can occur when using Extender on two devices with the same Apple ID. My theory is that only one device needs to submit the cert here, and so ignoring the error may be an allowable course of action.

Interestingly, revoking the user's current iOS Developer certificate allows this to be avoided, until the other device then attempts the same.

Full error:

```
provision.cpp:81
ios/submitDevelopmentCSR =7460
You already have a current iOS Development certificate or a pending certificate request.
```

**Comment by Matchstic** [comment]
I could in theory automatically revoke certificates when this error arises. However, this is too much of a workaround for my liking.

**Comment by Matchstic** [comment]
I added a temporary workaround for this issue in v0.3.2.

**Comment by Dollface3771** [comment]
I have Ext3nder (from julioverne) and/because I'm on iPhone 6s 9.3.3 Pangu (English version). So, when I go to the Pangu app to resign it, I'm giving several pop up messages. First is Apple Accout Au

**Comment by Dollface3771** [comment]
....cont. Authenticated, under that is the e-mail I use all the time, also with Cydia Impactor as well. Then another pop up, this error message...
Saved Photo
￼

**Comment by Dollface3771** [comment]
Cont.....The error message said, 
                      provision.cpp:81
                    ios/listAllDevelopmentCerts
                            =3170
                     Unable to find a team with
                       the given Team ID
                   'YN3GF3Y6DG' to which you
                 belong. Please contact Apple 
               Developer Program Support.
                   https://developer.apple.com/
                                 support

**Comment by Dollface3771** [comment]
and after all this I get a warning message (last line of the Pangu app in the installed section) As a result after I just got the Pangu app through Cydia Impactor, it seems to immediately expire,  after I reboot my iPhone. Pangu and all apps crash (No more Jailbreak). So, I have to re-install again with Cydia Impactor. I also tried  Please, help me out
                           
                              Thank you for all your

**Comment by Matchstic** [comment]
@Dollface3771 Sorry, but I do not provide support for Ext3nder. With regards to Cydia Impactor, you can revoke your certificates through that, which should hopefully resolve the immediate expiration issue.

**Comment by Dollface3771** [comment]
Thank you for your prompt response 😀, but I also tried that as a well. Still looking for more options...

**Comment by henpett1** [comment]
hey i have this isue i am trying add electra the jailbreak to my phone but it wont let me because of this problem is there a way to fix this?

**Comment by newbreedsoftware** [comment]
having same issue. Attached is a screenshot with debug menu on to show exactly what the app is getting hung on.
![poop](https://user-images.githubusercontent.com/28799062/38834636-e16786c8-417d-11e8-92b5-e52e47be74c6.jpg)

**Comment by Matchstic** [comment]
No longer an issue, as I don’t  need Extender as a base in the new-backend fork
