### ISSUE TITLE
Apple ID Listed as (null)

### ISSUE THREAD

**Issue by XeroAura** [Matchstic/Extender-Installer#7]
After logging in, the area showing the Apple ID first shows up as two blank cells. After about 30 seconds, it then switches to correct view (based on screenshots) but lists "Apple ID: (null)" in the first cell. However, signing still works afterwards.

**Comment by Matchstic** [comment]
This sounds like an UI issue I forgot to fix; it's totally fine, and can be fixed by switching tabs I believe.

**Comment by XeroAura** [comment]
Yes, it fixes itself after closing the app (well I rebooted to test out the resigned yalu).

**Comment by Matchstic** [comment]
Issue is fixed for v0.3.2
