### ISSUE TITLE
Popups after resigning are clicked away automatically

### ISSUE THREAD

**Issue by XeroAura** [Matchstic/Extender-Installer#8]
The app seems to autosubmit the login popup, but also clicks away for any errors afterwards. I got the popup that indicated I had to revoke my certs, but it was closed almost immediately.

**Comment by Matchstic** [comment]
This is completely normal, as errors are now routed to notification banners for display outside the app.

**Comment by XeroAura** [comment]
Ah ok. Just thought that some users might not know what that popup that closed immediately was for on first use since it doesn't trigger a banner while in app.
